INSERT INTO resource (id, resource_sub_type, region, price) VALUES (1, 'CPU - General Purpose', 'US East', 41) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (2, 'CPU - General Purpose', 'US West', 40) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (3, 'CPU - General Purpose', 'Europe', 46) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (4, 'GPU - NVIDIA T4', 'US East', 78) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (5, 'GPU - NVIDIA T4', 'US West', 80) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (6, 'GPU - NVIDIA T4', 'Europe', 82) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (7, 'High Memory Instance', 'US East', 64) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (8, 'High Memory Instance', 'US West', 63) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (9, 'High Memory Instance', 'Europe', 67) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (10, 'MySQL', 'US East', 30) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (11, 'MySQL', 'US West', 32) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (12, 'MySQL', 'Europe', 35) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (13, 'PostgreSQL', 'US East', 33) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (14, 'PostgreSQL', 'US West', 34) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (15, 'PostgreSQL', 'Europe', 36) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (16, 'MongoDB', 'US East', 37) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (17, 'MongoDB', 'US West', 39) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (18, 'MongoDB', 'Europe', 42) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (19, 'S3 / Object Storage', 'US East', 25) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (20, 'S3 / Object Storage', 'US West', 26) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (21, 'S3 / Object Storage', 'Europe', 28) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (22, 'Block Storage - SSD', 'US East', 29) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (23, 'Block Storage - SSD', 'US West', 30) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (24, 'Block Storage - SSD', 'Europe', 31) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (25, 'Block Storage - HDD', 'US East', 22) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (26, 'Block Storage - HDD', 'US West', 21) ON CONFLICT (id) DO NOTHING;
INSERT INTO resource (id, resource_sub_type, region, price) VALUES (27, 'Block Storage - HDD', 'Europe', 23) ON CONFLICT (id) DO NOTHING;
